// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef MainWindowUI_h
#define MainWindowUI_h
#include <FL/Fl.H>
void make_window();
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
#include "GLWindow.h"
#include <FL/Fl_Menu_Bar.H>
#include "SecondGLWindow.h"

class MainWindowUI {
public:
  MainWindowUI();
  Fl_Double_Window *mainWindow;
  Fl_Button *startButton;
  Fl_Button *clearButton;
  Fl_Text_Display *output;
  GLWindow *glWindow;
  Fl_Menu_Bar *menuBar;
  static Fl_Menu_Item menu_menuBar[];
  static Fl_Menu_Item *statesMenu;
  SecondGLWindow *secondGLWindow;
};
#endif
