// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "MainWindowUI.h"

void make_window() {
}

MainWindowUI::MainWindowUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = mainWindow = new Fl_Double_Window(1164, 631);
    w = o;
    o->user_data((void*)(this));
    startButton = new Fl_Button(15, 570, 90, 25, "Start");
    clearButton = new Fl_Button(730, 570, 90, 25, "Clear");
    output = new Fl_Text_Display(730, 15, 420, 545);
    { GLWindow* o = glWindow = new GLWindow(15, 14, 705, 546);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NO_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    o->end();
    o->resizable(o);
  }
}
